version: '3.1'

services:
  badcaller:
    image: index.docker.io/xcession2k/badcaller:latest
    restart: always
    ports:
      - 80:8080
    expose:
      - 80
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
  watchtower:
    image: v2tec/watchtower:armhf-latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/.docker/config.json:/config.json
    command: --interval 30
