version: "3.1"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data:/tmp/pg
    env_file:
      - docker.env
 
  adminer:
    image: adminer
    ports:
      - 8090:8080
