version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: badcaller

  adminer:
    image: adminer
    ports:
      - 8090:8080

# This syntax required by WSL
volumes:
  postgres-vol:
